f_rawbulk.c: Include missing header <linux/usb/gadget.h>
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `rawbulk_function_bind':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:179: undefined reference to `usb_interface_id'
aarch64-webos-linux-ld.bfd: /usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:194: undefined reference to `usb_ep_autoconfig'
aarch64-webos-linux-ld.bfd: /usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:201: undefined reference to `usb_ep_autoconfig'
aarch64-webos-linux-ld.bfd: /usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:214: undefined reference to `usb_copy_descriptors'
aarch64-webos-linux-ld.bfd: /usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:187: undefined reference to `usb_string_id'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `do_activate':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:254: undefined reference to `config_ep_by_speed'
aarch64-webos-linux-ld.bfd: /usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:266: undefined reference to `config_ep_by_speed'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `rawbulk_attr_release':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:398: undefined reference to `usb_put_function_instance'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `alloc_inst_rawbulk':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:432: undefined reference to `config_group_init_type_name'
aarch64-webos-linux-ld.bfd: /usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:432: undefined reference to `config_group_init_type_name'
aarch64-webos-linux-ld.bfd: /usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:432: undefined reference to `config_group_init_type_name'
aarch64-webos-linux-ld.bfd: /usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:432: undefined reference to `config_group_init_type_name'
aarch64-webos-linux-ld.bfd: /usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:432: undefined reference to `config_group_init_type_name'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `rawbulk_bind_config':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:381: undefined reference to `usb_add_function'
aarch64-webos-linux-ld.bfd: /usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:362: undefined reference to `usb_string_id'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `alloc_inst_rawbulk':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:432: undefined reference to `config_group_init_type_name'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `via_modemmod_init':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:474: undefined reference to `usb_function_register'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `via_etsmod_init':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:487: undefined reference to `usb_function_register'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `via_atcmod_init':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:500: undefined reference to `usb_function_register'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `via_pcvmod_init':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:513: undefined reference to `usb_function_register'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `via_gpsmod_init':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:526: undefined reference to `usb_function_register'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `via_modemmod_exit':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:474: undefined reference to `usb_function_unregister'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `via_etsmod_exit':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:487: undefined reference to `usb_function_unregister'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `via_atcmod_exit':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:500: undefined reference to `usb_function_unregister'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `via_pcvmod_exit':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:513: undefined reference to `usb_function_unregister'
aarch64-webos-linux-ld.bfd: drivers/built-in.o: in function `via_gpsmod_exit':
/usr/src/kernel/drivers/misc/mediatek/c2k_usb/f_rawbulk.c:526: undefined reference to `usb_function_unregister'